# Generated by Django 6.0.6 on 2026-07-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_upvotes_alter_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mood',
            field=models.CharField(choices=[('hopeful', '😊 Hopeful'), ('struggling', '😔 Struggling'), ('grateful', '❤️ Grateful'), ('celebrating', '🎉 Celebrating'), ('reflecting', '🤔 Reflecting'), ('frustrated', '😡 Frustrated'), ('motivated', '💪 Motivated'), ('healing', '🌱 Healing')], default='reflecting', max_length=20),
        ),
    ]
