# Generated by Django 6.0.6 on 2026-07-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_mood'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('storytelling', '📖 Storytelling'), ('personal_growth', '🌱 Personal Growth'), ('relationships', '❤️ Relationships'), ('school', '🎓 School'), ('career', '💼 Career'), ('family', '👨\u200d👩\u200d👧 Family'), ('mental_health', '🧠 Mental Health'), ('travel', '🌍 Travel'), ('success', '🎉 Success'), ('loss', '💔 Loss'), ('hobbies', '🎮 Hobbies')], default='storytelling', max_length=30),
        ),
    ]
